FROM ubuntu:18.04

RUN apt-get update && apt install -y python3-pip python3-dev nodejs npm curl vim tree
RUN pip3 install jinja2 ipython python-slugify

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs

